# Generated by Django 2.2.26 on 2022-06-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPaymentMethodScreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=256)),
                ('lastname', models.CharField(max_length=256)),
                ('emailaddress', models.EmailField(max_length=254)),
                ('creditcardnumber', models.CharField(max_length=256)),
                ('ccv', models.IntegerField()),
                ('expirationdate', models.DateField()),
            ],
        ),
    ]
